dist: xenial
sudo: required

matrix:
  include:
    - os : osx
      osx_image: xcode12
    - os : osx
      osx_image: xcode11.3
    - os: linux
      sudo: required
    - os: windows
      language: cpp

jobs:
  allow_failures:
    - os: windows

branches:
  only:
    - master
    - devel

services:
  - docker

notifications:
  email:
    recipients:
      - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd scripts && ./build_wheels_osx.sh); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd scripts && make) ; fi
